---
language: node_js

node_js:
- "v5.4.0"
- "v0.12.0"

script:
- npm run coverage

cache:
  directories:
    - node_modules

before_script:
  - "export PATH=$PATH:node_modules/.bin"
  - "node-gyp rebuild"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-4.8 -y