name: Build

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        version: 16.x
    - run: npm install -g node-gyp yarn

    - name: Install Dependencies
      run: yarn install
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test

    - name: Report Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
